version: 2
updates:
  - package-ecosystem: 'npm'
    # Files stored in `app` directory
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        patterns:
          - "*"
