description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
